### ISSUE TITLE
[DevOps] - Clang format Embedded Base

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Embedded-Base#141]
### Description

Right now, you cannot clang format embedded base.  This is because the clang format file in vscode for each dev is hardcoded to `./Drivers/Embedded-Base/clang-format`, which obviously requires a different approach.

### Acceptance Criteria

Clang format embedded base in a way that can also apply to cerb and shep, so you have one format file and one way to set it up across all 3 repos.

### Proposed Solution

Idk, maybe just setup embedded base to use the implicit clang format?

**Comment by dyldonahue** [comment]
should be fixed by pre commit hooks
