### ISSUE TITLE
[CANGEN] - Switch to JSON

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Embedded-Base#161]
### Description

Switch to JSON

### Acceptance Criteria

We use JSON instead

### Proposed Solution

python `import json`

**Comment by harrison-e** [comment]
Just completed `jsongen`, which is a python script that converts all of the YAML files in `can-messages/` to JSON. You can see the script and all of the converted files on the `yaml2json` branch of Embedded-Base.

Next step is to make RustSynth and calypsogen work with JSON over YAML.

**Comment by harrison-e** [comment]
YAML removed, JSON added to `cangen/can-messages/`

`jsongen` properly converts YAML to JSON

YAML gone

See Calypso for changes to `calypsogen.py`
