### ISSUE TITLE
[DevOps] - Improve Autoformatting Experience

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Embedded-Base#53]
### Description

Right now we have clang-format built into the docker container, and we have a basic .clang-format file in the repo. What we need to do is:
1. Replace clang-format contents with the one shown here that is more updated to our tastes, attached here
2. Give it a bash alias in the Dockerfile. [See this PR for reference on how to do that](https://github.com/Northeastern-Electric-Racing/Cerberus/pull/59)
[clang-format.txt](https://github.com/Northeastern-Electric-Racing/Cerberus/files/12849223/clang-format.txt)

There is also a weird bug on Linux where the autoformatter run on a local file will result in the permissions being changed for the file, not allowing the user to make any changes to the file without running sudo again.

### Acceptance Criteria

Docker image builds and successfully aliases the command.

### Proposed Solution

Command to do this is clang-format -style=file -i whateverfile.c so just alias the first part up to whatever.c

**Comment by dyldonahue** [comment]
Stealing this ticket to represent integrating pre hook to automatically run clang. Pending python venv setup
