### ISSUE TITLE
[Driver] - ADS131M04 Driver

### ISSUE THREAD

**Issue by nwdepatie** [Northeastern-Electric-Racing/Embedded-Base#83]
### Current Features

We have existing drivers, to reference. This chip communicates over SPI and has an interrupt so we should look at the LTC6820 driver for SPI best practices

### Desired Additional Features

Look at datasheet and implement driver accordingly. https://www.ti.com/lit/ds/symlink/ads131m04-q1.pdf?ts=1708731874014&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FADS131M04-Q1%252Fpart-details%252FADS131M04QPWRQ1

**Comment by RChandler234** [comment]
![image](https://github.com/Northeastern-Electric-Racing/Embedded-Base/assets/29521172/08d6aa49-ded4-44c5-b1ce-6656f16e4c69)
